# Generated by Django 5.1.2 on 2024-10-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='user',
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('DEV', 'Developpeur'), ('RH', 'Ressources Humaines'), ('MARKETING', 'Responsable Marketing')], max_length=30),
        ),
    ]
