# Generated by Django 5.1.2 on 2024-10-11 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_remove_employe_user_alter_employe_poste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='prenom',
        ),
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
